// We list the icons we use explicitly because this reduces our bundle size.

import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleDoubleDown,
  faArrowLeft,
  faBars,
  faBookOpen,
  faBullhorn,
  faCamera,
  faCircle,
  faCoffee,
  faCog,
  faCalendarAlt,
  faCrown,
  faEnvelope,
  faEye,
  faGavel,
  faGift,
  faHandHoldingHeart,
  faHandsHelping,
  faHashtag,
  faHome,
  faInfoCircle,
  faLeaf,
  faLink,
  faLock,
  faLockOpen,
  faPlus,
  faQuestionCircle,
  faReply,
  faSearch,
  faShoppingCart,
  faSignOutAlt,
  faSpinner,
  faSync,
  faTimesCircle,
  faTrashAlt,
  faUser,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faAngleDoubleDown,
  faArrowLeft,
  faBars,
  faBookOpen,
  faBullhorn,
  faCamera,
  faCircle,
  faCoffee,
  faCog,
  faCalendarAlt,
  faCrown,
  faEnvelope,
  faEye,
  faGavel,
  faGift,
  faHandHoldingHeart,
  faHandsHelping,
  faHashtag,
  faHome,
  faInfoCircle,
  faLeaf,
  faLink,
  faLock,
  faLockOpen,
  faPlus,
  faQuestionCircle,
  faReply,
  faSearch,
  faShoppingCart,
  faSignOutAlt,
  faSpinner,
  faSync,
  faTimesCircle,
  faTrashAlt,
  faUser
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('VIcon', FontAwesomeIcon)
})
