# .github/workflows/azure.yml
name: Azure Functions (for SSR)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: npm run build
        env:
          NITRO_PRESET: azure-functions
          IZNIK_API_V1: https://fdapilive.ilovefreegle.org/api
          IZNIK_API_V2: https://api.ilovefreegle.org:8192/apiv2

#      - name: Zip output
#        uses: montudor/action-zip@v1
#        with:
#          args: zip -qq -r .output/deploy.zip .output
#
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: Freegle
          package: .output/deploy.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}